# Generated by Django 6.0 on 2026-02-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_payment_mode_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('UPI', 'UPI'), ('CARD', 'Card'), ('NETBANKING', 'Net Banking')], default='COD', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='Stock',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product_image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
