# Generated by Django 6.0 on 2026-02-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=255)),
                ('Category', models.CharField(blank=True, max_length=100)),
                ('Brand', models.CharField(blank=True, max_length=100)),
                ('Model_Type', models.CharField(blank=True, max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Unit_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Gst_Percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ProductImage', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
