# Generated by Django 6.0 on 2026-02-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Total_Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductImage',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
