# Generated by Django 6.0 on 2026-02-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_alter_product_total_price_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='adminpanel_product',
        ),
    ]
