# Generated by Django 6.0 on 2026-02-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmessage_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='full_name',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='No Subject', max_length=200),
            preserve_default=False,
        ),
    ]
