# Generated by Django 6.0 on 2026-02-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='register',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterModelTable(
            name='register',
            table='register',
        ),
    ]
